### ISSUE TITLE
support gradle >5.0

### ISSUE THREAD

**Issue by 123Haynes** [jerzykrlk/jcstress-gradle-plugin#18]
Currently, this plugin does not work with gradle >5.0.  
It fails with:  

```
> Task :integrationTest

com.github.erizo.gradle.JcstressPluginForkedTestSpec > should complete a forked run FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at JcstressPluginForkedTestSpec.groovy:39

com.github.erizo.gradle.JcstressPluginIncludeTestsSpec > should include a test class a simple run FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at JcstressPluginIncludeTestsSpec.groovy:39

com.github.erizo.gradle.JcstressPluginUnforkedTestSpec > should complete an unforked run FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at JcstressPluginUnforkedTestSpec.groovy:39

```

```
* Exception is:
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':jcstressJar'.
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:44)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.InvalidUserDataException: Value 'jcstress classes' specified for property '$1' cannot be converted to a directory.
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:67)
	... 28 more


* Get more help at https://help.gradle.org

BUILD FAILED in 7s
3 actionable tasks: 3 executed

	at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:237)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:234)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:298)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:234)
	at com.github.erizo.gradle.JcstressPluginForkedTestSpec.runGradleTask(JcstressPluginForkedTestSpec.groovy:39)
	at com.github.erizo.gradle.JcstressPluginForkedTestSpec.should complete a forked run(JcstressPluginForkedTestSpec.groovy:32)
```

**Comment by jerzykrlkroche** [comment]
Hi, thank you for the report! I'll look into it after the weekend.

**Comment by 123Haynes** [comment]
@jerzykrlkroche awesome :)  Note that to get to this error you first need to remove the wrapper task from all build.gradle files, because gradle now defines that internally.  
Otherwise gradle will error that the wrapper task already exists.

**Comment by jerzykrlk** [comment]
I know it's taking a while. I think I've tracked down an issue to a single line where output of a task is passed to another one, which apparently behaves differently in >5:
```
jcstressJarTask.getInputs().dir(jcstressSourceSet.getOutput());
```
Any thoughts? If not, then I'm afraid I've come to a point where I'm going to have to read the manual :)

**Comment by jerzykrlk** [comment]
Which leads me to this paragraph:
```
The TaskInputs.dir(Object) method can no longer be called with an argument that resolves to anything other than a single directory.
```
I will need to spend some time reading instructions, now. Sorry... :/

**Comment by 123Haynes** [comment]
Unfortunately, I know next to nothing about plugin development for gradle, so I can't help 😢

**Comment by EmMper** [comment]
Hope this will help:
https://github.com/google/protobuf-gradle-plugin/issues/311

**Comment by jerzykrlk** [comment]
I think it's fixed now - there was an API change and also annotation processor is now invoked differently. 

Can anyone have a look here: https://github.com/jerzykrlk/jcstress-gradle-plugin/pull/19 , before I merge, to be sure? I'll merge it and release after the weekend. 

Thanks for help!

**Comment by jerzykrlk** [comment]
Okay, I've released version 0.8.3 with support for both Gradle 4 and 5.

**Comment by 123Haynes** [comment]
@jerzykrlk Thank you 👍   
Did you publish the new release to the gradle plugin repo as well?

https://plugins.gradle.org/plugin/com.github.erizo.gradle.jcstress

lists 0.8.1-SNAPSHOT as the latest version.

**Comment by jerzykrlkroche** [comment]
Hi there.
I'm not maintaining that actively. I recall that I tried to publish that once and something failed. 

Thanks for the reminder - I'll try that.
