### ISSUE TITLE
jcstressJar is missing TestList

### ISSUE THREAD

**Issue by carl-mastrangelo** [jerzykrlk/jcstress-gradle-plugin#20]
When trying to run with jcstress-gradle-plugin, The generated jar is missing the BenchmarkList file under META-INF.  This causes the JCStress to throw an NPE:

```
   ...
  Solo stride size will be autobalanced within [10, 10000] elements, but taking no more than 100 Mb.

Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:167)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at org.openjdk.jcstress.infra.runners.TestList.getTests(TestList.java:53)
        at org.openjdk.jcstress.infra.runners.TestList.tests(TestList.java:105)
        at org.openjdk.jcstress.JCStress.getTests(JCStress.java:139)
        at org.openjdk.jcstress.JCStress.run(JCStress.java:67)
        at org.openjdk.jcstress.Main.main(Main.java:60)

> Task :jcstress FAILED
```

Steps to reproduce:

1.  `git clone https://github.com/carl-mastrangelo/perfmark.git`
2.  `cd perfmark`
3.  `./gradlew :perfmark-java9:jcstress`

Thanks in advance

**Comment by jerzykrlk** [comment]
Hi @carl-mastrangelo - I've just released version 0.8.3 that solved same issue with Gradle 5, and should also solve your problem.

I've ran your suite with new version and it works on my machine - can you upgrade and check?

**Comment by carl-mastrangelo** [comment]
@jerzykrlk Works great!  Thanks for the fast turn around time!

**Comment by jerzykrlk** [comment]
You're welcome. I'm happy to see that someone is actually using the plugin.
:)

śr., 15 maj 2019, 00:46 użytkownik Carl Mastrangelo <
notifications@github.com> napisał:
